#pragma once

// Implementation of wmsc files generated by Cobra (https://github.com/RoadrunnerWMC/Cobra)

#define COBRA_MAGIC "WMS"
#define COBRA_VERSION '0'
#define COBRA_GAME 'W'

#include <types.h>

// (Same struct as native script commands)
struct ScriptCommand {
    u32 id;
    u32 argument;
};

// (Same struct as native scripts-table entries)
struct ScriptsTableEntry {
    ScriptCommand *start;  // offset relative to start of .wmsc file
};

struct WMSCFile {
    char magic[3];  // "WMS"
    char version;  // Current version: '0' (as a character, not byte value
                   // zero). If version is unrecognized, consider everything
                   // beyond this point unparseable.
    char game;  // - 'W' = NSMBW
                // - '2' = NSMB2
                // - 'U' = NSMBU or NSLU (on Wii U)
                // - 'X' = NSMBUDX
                // From this, you can infer endianness, and whether the
                // scriptsTableEntry struct (above) includes priorities or not.
                // If you load a .wmsc into the wrong game, the loader can
                // panic instead of trying to read it.
    char gameVariant[3];  // Game variant identifier, so that loading a .wmsc
                          // file into the wrong version of a game can be
                          // detected. The list of game variants is defined
                          // elsewhere.
                          // If you load a .wmsc into the wrong game variant,
                          // the loader can panic instead of trying to read it.
    u32 fileSize;  // total file size, including all header stuff
    u32 numScripts;
    u32 *scriptIDs;  // Guaranteed to be in sorted order so
                     // that binary searching is valid
    ScriptsTableEntry *scriptsTable;
    ScriptCommand *scriptsData;  // all of the commands data goes here
};