#include <kamek.h>
#include <propelparts/bases/d_cobra_script_loader.hpp>
#include <propelparts/bases/d_custom_profile.hpp>
#include <game/mLib/m_allocator_dummy_heap.hpp>

#include <game_versions_nsmbw.h>

#ifdef IS_GAME_VERSION_DYNAMIC
#error Dynamic compilation is unsupported for this patch.
#endif

#if GAME_VERSION < GAME_VERSION_K
#define SCRIPT_FILE "scripts"
#define COBRA_VARIANT "v1_"
#else
#define SCRIPT_FILE "scripts_K"
#define COBRA_VARIANT "v3_"
#endif

/*
    A loader for custom worldmap sequence scripts.
    This takes a .wmsc file generated by RoadrunnerWMC's Cobra (https://github.com/RoadrunnerWMC/Cobra)
    Any scripts located inside will replace the original game's version of that script.
    In theory, entirely new scripts can also be loaded from this file.
    NOTE: Because Nintendo added new sequence commands for the Korean version, Korea, Taiwain, and China load their own unique script file
    Unless you are modifying smc_demo_Pause_Menu, smc_demo_Stock_Menu, and smc_demo_WorldSelect_Menu, the script files will be identical outside of game variant
*/

dCobraScriptLoader_c *dCobraScriptLoader_c::m_instance = nullptr;

CUSTOM_BASE_PROFILE(COBRA_SCRIPT_LOADER, dCobraScriptLoader_c, fProfile::COBRA_SCRIPT_LOADER, fProfile::DRAW_ORDER::DUMMY_ACTOR);

dCustomProfile_c l_COBRA_SCRIPT_LOADER_profile(&g_profile_COBRA_SCRIPT_LOADER, "COBRA_SCRIPT_LOADER", fProfile::COBRA_SCRIPT_LOADER);

int dCobraScriptLoader_c::create() {
    int entrynum = DVDConvertPathToEntrynum("/WorldMap/" SCRIPT_FILE ".wmsc");
    if (entrynum == -1) {
        OSReport("/WorldMap/" SCRIPT_FILE ".wmsc not found, falling back to original game scripts!\n");
        return SUCCEEDED;
    }

    void *scriptBuffer = mScriptLoader.request("/WorldMap/" SCRIPT_FILE ".wmsc", 0, mHeap::g_archiveHeap);
    if (scriptBuffer != nullptr) {
        mAllocator.createFrmHeap(-1, mHeap::g_gameHeaps[mHeap::GAME_HEAP_DEFAULT], 0, 0x20);
        loadScriptFile(scriptBuffer);
        mAllocator.adjustFrmHeap();
    }
    return scriptBuffer != nullptr;
}

int dCobraScriptLoader_c::doDelete() {
    m_instance = nullptr;
    if (mAllocator.mpHeap != mAllocatorDummyHeap_c::getInstance()) {
        mScriptLoader.freeResouce();
    }
    return SUCCEEDED;
}

void dCobraScriptLoader_c::loadScriptFile(void *scriptBuffer) {
    WMSCFile header = *(WMSCFile *)scriptBuffer;

    // Header validity checks
    if (memcmp(header.magic, COBRA_MAGIC, sizeof(header.magic)) != 0) {
        OSReport("Invalid map script header magic!\n");
        return;
    }
    if (header.version != COBRA_VERSION) {
        OSReport("The map script file version is not supported! Only wmsc version %c is supported.\n", COBRA_VERSION);
        return;
    }
    if (header.game != COBRA_GAME) {
        OSReport("The map script file is for the wrong game! Only wmsc game %c is supported.\n", COBRA_GAME);
        return;
    }
    if (memcmp(header.gameVariant, COBRA_VARIANT, sizeof(header.gameVariant)) != 0) {
        OSReport("The map script file is for the wrong game version! Only wmsc game version %s is supported.\n", COBRA_VARIANT);
        return;
    }

    // Assign header data if file is valid
    memcpy(mScriptFile.magic, header.magic, sizeof(header.magic));
    mScriptFile.version = header.version;
    mScriptFile.game = header.game;
    memcpy(mScriptFile.gameVariant, header.gameVariant, sizeof(header.gameVariant));
    mScriptFile.numScripts = header.numScripts;
    mScriptFile.fileSize = header.fileSize;

    // Assign rest of file
    u32 *scriptIDs = (u32 *)((u8 *)scriptBuffer + 16);

    ScriptsTableEntry *scriptsTable = (ScriptsTableEntry *)((u8 *)scriptBuffer + 16 + header.numScripts * sizeof(u32));

    ScriptCommand *scriptsData = (ScriptCommand *)((u8 *)scriptsTable + header.numScripts * sizeof(ScriptsTableEntry));

    for (u32 i = 0; i < header.numScripts; i++) {
        scriptsTable[i].start = (ScriptCommand *)((u8 *)scriptBuffer + (u32)scriptsTable[i].start);
    }

    mScriptFile.scriptIDs = scriptIDs;
    mScriptFile.scriptsTable = scriptsTable;
    mScriptFile.scriptsData = scriptsData;
}

bool dCobraScriptLoader_c::isCustomScript(u32 scriptID) const {
    for (u32 i = 0; i < mScriptFile.numScripts; i++) {
        if (mScriptFile.scriptIDs[i] == scriptID) {
            return true;
        }
    }
    return false;
}

s32 dCobraScriptLoader_c::findScriptIndex(u32 scriptId) const {
    u32 *ids = mScriptFile.scriptIDs;
    s32 lo = 0;
    s32 hi = (s32)mScriptFile.numScripts - 1;

    while (lo <= hi) {
        s32 mid = (lo + hi) / 2;
        if (ids[mid] == scriptId) {
            return mid;
        } else if (ids[mid] < scriptId) {
            lo = mid + 1;
        } else {
            hi = mid - 1;
        }
    }

    return -1;
}